version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pos_postgres
    environment:
      POSTGRES_DB: pos_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pos_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pos_backend
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/pos_system
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_REFRESH_SECRET: your-super-secret-refresh-key-change-in-production
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - pos_network
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pos_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - pos_network

volumes:
  postgres_data:

networks:
  pos_network:
    driver: bridge